version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
     - "3000:3000"

  team-blue:
    build: ./team-blue
    ports:
     - "3001:3001"

  team-green:
    build: ./team-green
    ports:
     - "3002:3002"

  team-red:
    build: ./team-red
    ports:
     - "3003:3003"

  team-orange:
    build: ./team-orange
    ports:
     - "3004:3004"

  auth:
    build: ./auth
    ports:
     - "3005:3005"

  historical:
    build: ./historical
    ports:
     - "3006:3006"
