apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: historical
  name: historical
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: historical
    spec:
      containers:
      - image: historical
        name: historical
        imagePullPolicy: Never
        ports:
        - containerPort: 3006
        resources: {}
      restartPolicy: Always
status: {}
