apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: team-blue
  name: team-blue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: team-blue
    spec:
      containers:
      - image: team-blue
        name: team-blue
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
